name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: v2-dependencies--${{ matrix.node-version }}-${{ runner.OS }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v2-dependencies--${{ matrix.node-version }}-${{ runner.OS }}-
            v2-dependencies--${{ matrix.node-version }}-

      - name: Install Dependencies
        run: yarn install --prefer-offline --pure-lockfile

      - name: Check prettier
        run: yarn run lint:prettier

      - uses: GoogleCloudPlatform/release-please-action@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action

      - name: Publish to Visual Studio Marketplace
        if: ${{ github.ref == 'refs/heads/main' && steps.release.outputs.release_created }}
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
